const mongoose=require("../db/mongoDB");
const {Schema}=mongoose;
const NewHrApplicantSchema=new Schema({
        full_name:{
            type:String,
            required:true,
        },
        email:{
            type:String,
            required:true,
        },
        password:{
            type:String,
            required:true,
        },
        hr_round_id:{
            type:mongoose.ObjectId,
            default:null,
        },
        primary_mobile_number:{
            type:String,
            required:true,
        },
        alt_mobile_number:{
            type:String,
            required:true,
        },
        profile_picture:{
            type:Object,
            default:{}
        },
        cv:{
            type:Object,
            required:true
        },
        position:{
            type:String,
            required:true,
        },
        hr_team_id:{
            type:mongoose.ObjectId,
            default:null,
        },
        location:{
            type:String,
            required:true,
        },
        status:{
            type:String,
            default:"Applied"
        }
    },
    {
        timestamps:true,
    });
module.exports=mongoose.model("new_hr_applicant",NewHrApplicantSchema);